import "./globals.css";
import { LanguageProvider } from "@/components/LanguageProvider";
import LayoutShell from "@/components/LayoutShell";

export const metadata = {
  title: "Reflecta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <LanguageProvider>
          <LayoutShell>{children}</LayoutShell>
        </LanguageProvider>
      </body>
    </html>
  );
}
