import "./globals.css";
export const metadata = {
  title: "Reflecta",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={``}>
        <div className="">
          <header className="flex items-center justify-around px-1 py-4 h-16 shadow-lg ">
            <h1 className="text-xl font-extrabold text-indigo-700">Reflecta</h1>
          </header>
          {children}
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
