import "./globals.css";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Reflecta",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={``}>
      <Toaster/>
        <div className="">
          <header className="flex items-center justify-around px-1 py-4 h-16 shadow-lg mb-16">
            <h1 className="text-xl font-extrabold text-indigo-700">Reflecta</h1>
          </header>
          <div className="px-3">{children}</div>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
